config/routes.rb
Rails.application.routes.draw do

  get 'list_items/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'

  resources :lists, except: [:show] do 
    member do 
      put :soft_destroy 
      put :restore
    end 
    collection do
      get :thrash
    end 
    resources :list_items
  end 
  resources :list_items do
    member do 
      put :soft_destroy 
    end 
    resources :taggings do 
      collection do 
        put ":tag_id/soft_destroy"   =>   "taggings#soft_destroy", as: "soft_destroy"
        put ":tag_id/restore"        =>   "taggings#restore", as: "restore"
      end 
    end 
  end 

  namespace :api do
    namespace :v1 do
      get ':owner_name/articles'          =>  "owners/articles#articles_by_owner_name"
      resources :articles, only: [:show]
      resources :owners, only: [:index]
      get ':owner_name'                    => "owners#show"
    end 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :owner

    def get_price_with_currency
        self.price.to_s + self.currency
    end
end

app/models/concerns/soft_destroyer.rb
module SoftDestroyer

		def soft_destroy
			self.update(deleted_at: Time.now)
			run_callbacks :soft_destroy do 
			end unless self.class.name == "Tagging"
		end
	
		def restore
			self.update(deleted_at: nil)
			run_callbacks :restore do
			end unless self.class.name == "Tagging"
		end
end 

app/models/list.rb
class List < ApplicationRecord

    include SoftDestroyer

    extend ActiveModel::Callbacks
    define_model_callbacks :soft_destroy, :restore, only: [:after]
    after_soft_destroy :soft_destroy_list_items
    after_restore :restore_list_items

    has_many :list_items, dependent: :destroy
    validates :name, presence: true


    scope :active, -> {where('deleted_at IS NULL')}
    scope :soft_destroyed, -> {where('deleted_at IS NOT NULL')}

    def soft_destroy_list_items
        self.list_items.each {|list_item| list_item.soft_destroy }
    end 

    def restore_list_items
        self.list_items.each {|list_item| list_item.restore }
    end 

end

app/models/list_item.rb
class ListItem < ApplicationRecord
	include SoftDestroyer
	extend ActiveModel::Callbacks
	define_model_callbacks :soft_destroy, :restore, only: [:after]
	after_soft_destroy :soft_destroy_taggings
	after_restore :restore_taggings

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :current_tags ,-> {where('deleted_at IS NULL')} ,foreign_key: "tag_id", source: :tag, through: :taggings
	has_many :removed_tags ,-> {where('deleted_at IS NOT NULL')} ,foreign_key: "tag_id", source: :tag, through: :taggings

	validates :name, presence: true

	belongs_to :list

	scope :active, -> {where('deleted_at IS NULL')}
	scope :soft_destroyed, -> {where('deleted_at IS NOT NULL')}


	def soft_destroy_taggings
		self.taggings.each {|tagging| tagging.soft_destroy }
	end 

	def restore_taggings
		self.taggings.each {|tagging| tagging.restore }
	end 
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_many :articles
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    
    has_many :taggings
    has_many :list_items, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
    include SoftDestroyer
    belongs_to :tag
    belongs_to :list_item
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
end 

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::ApiController

    def show
        @article = Article.find(params[:id])
    end 
end 

app/controllers/api/v1/owners/articles_controller.rb
class Api::V1::Owners::ArticlesController < Api::V1::ApiController

	def articles_by_owner_name
		@owner = Owner.find_by(name: params[:owner_name])
	end 
end 

app/controllers/api/v1/owners_controller.rb
class Api::V1::OwnersController < Api::V1::ApiController
    def index
        @owners = Owner.limit(params[:length]).offset(params[:offset])
    end 

    def show
        @owner = Owner.find_by(name: params[:owner_name])
    end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :soft_destroy]

  def show
  end

  
  def soft_destroy
    @list_item.soft_destroy
    redirect_to root_path
  end

  private 

  def set_list_item
    @list_item = ListItem.find(params[:id])
  end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [:edit, :update, :destroy, :soft_destroy, :restore]

  def index
    @lists = List.active
  end

  def thrash
    @lists = List.soft_destroyed
  end 

  def new 
    @list = List.new
  end 

  def create
    @list = List.new(list_params)
      if @list.save
        redirect_to root_path
      else
        render :new 
      end
  end 

  def edit
  end

  def update
      if @list.update(list_params)
        redirect_to root_path
      else
        render :edit
      end
  end

  def soft_destroy
    @list.soft_destroy
    redirect_to root_path
  end 

  def restore
    @list.restore
    redirect_to thrash_lists_path
  end 

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private 

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
    before_action :set_tagging, only: [:soft_destroy, :restore]

  def soft_destroy
      @tagging.soft_destroy
      @list_item = ListItem.find(params[:list_item_id])
      redirect_to list_list_item_path(id: @list_item, list_id: @list_item.list.id)
    end 
  
    def restore
      @tagging.restore
      @list_item = ListItem.find(params[:list_item_id])
      redirect_to list_list_item_path(id: @list_item, list_id: @list_item.list.id)
    end 
  
    private 
  
    def set_tagging
      @tagging =Tagging.find_by(tag_id: params[:tag_id],list_item_id: params[:list_item_id] )
    end

    def tagging_params
      params.require(@tagging).permit(:tag_id,:list_item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReserveTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_items/show.html.erb
<b><%= button_to 'Active Lists', root_path, method: :get %></b>
<br>
<h2><%= @list_item.name%></h2><br>

<b>assigned tags:</b>
<table>
	<tbody>
			<% @list_item.current_tags.each do |tag| %>
			<tr>
				<td>-<%= tag.name %></td>
				<td><%= button_to 'Soft Destroy',soft_destroy_list_item_taggings_path(list_item_id: @list_item.id, tag_id: tag.id ), method: :put,data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
	</tbody>
<table>
<br>

<b>removed tags:</b>
<table>
	<tbody>
			<% @list_item.removed_tags.each do |tag| %>
			<tr>
				<td>-<%= tag.name %></td>
				<td><%= button_to 'Restore',restore_list_item_taggings_path(list_item_id: @list_item.id, tag_id: tag.id ), method: :put,data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
	</tbody>
<table>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<b><%= button_to 'New List', new_list_path, method: :get %></b>
<br>
<b><%= button_to 'Thrash Lists', thrash_lists_path, method: :get %></b>


<h1>Lists</h1>
<table>
  <tbody>
	<% @lists.each do |list| %>
	  <tr>
			<td><h3><%= list.name %><h3></td>
			<td><%= button_to 'Edit', edit_list_path(list), method: :get %></td>
			<td><%= button_to 'Soft Destroy',{ action: "soft_destroy", id: list.id }, method: :put %></td>
			<td><%= button_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	</tbody>
</table>
	  <table>
			<tbody>
				<% list.list_items.active.each do |list_item| %>
					<tr>
						<td><b><%= list_item.name %></b></td>
						<td><%= button_to 'View', list_list_item_path(id: list.id, list_id: list_item.list.id), method: :get %></td>
						<td><%= button_to 'Edit', edit_list_list_item_path(id: list.id, list_id: list_item.list.id), method: :get %></td>
						<td><%= button_to 'Soft Destroy',soft_destroy_list_item_path(list_item.id), method: :put %></td>
						<td><%= button_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<tr>
						<td>tags: <%= list_item.current_tags.map{|tag| tag.name}%></td>
					</tr>
				<% end %>
			</tbody>
		<table>
		<hr>
	<% end %>
<br>

app/views/lists/new.html.erb
<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/thrash.html.erb
<b><%= button_to 'Active Lists', root_path, method: :get %></b>
<h1>Thrash Lists</h1>
<table>
  <tbody>
	<% @lists.each do |list| %>
	  <tr>
			<td><h3><%= list.name %><h3></td>
			<td><%= button_to 'Restore List', { action: "restore", id: list.id }, method: :put %></td>
			<td><%= button_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	</tbody>
</table>
	  <table>
			<tbody>
				<% list.list_items.soft_destroyed.each do |list_item| %>
					<tr>
						<td><%= list_item.name %></td>
						<td>- <%= list_item.deleted_at.nil? ? "false" : "deleted" %></td>
						<td><%=list_item.tags.map{|tag| tag.name}%></td>
					</tr>
				<% end %>
			</tbody>
		<table>
		<hr>
	<% end %>
<br>